//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtADNCodigo
    {
        public int Id { get; set; }
        public string Tipo { get; set; }
        public string Base { get; set; }
        public string Color { get; set; }
        public string Veta { get; set; }
        public string Cubrecanto { get; set; }
        public string Jaladera { get; set; }
        public string PosicionJaladera { get; set; }
        public string Variante { get; set; }
        public string Codigo { get; set; }
        public string Descripcion1 { get; set; }
        public string Descripcion2 { get; set; }
        public Nullable<double> Impuesto1 { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> PrecioLista { get; set; }
        public Nullable<decimal> Precio2 { get; set; }
        public Nullable<decimal> Precio3 { get; set; }
        public Nullable<decimal> Precio4 { get; set; }
        public Nullable<decimal> Precio5 { get; set; }
        public Nullable<decimal> Precio6 { get; set; }
        public Nullable<decimal> Precio7 { get; set; }
        public Nullable<decimal> Precio8 { get; set; }
        public Nullable<decimal> Precio9 { get; set; }
        public Nullable<decimal> Precio10 { get; set; }
        public Nullable<double> Factor { get; set; }
        public string Estatus { get; set; }
        public Nullable<decimal> PrecioAdjuntos { get; set; }
    }
}
