//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtColore
    {
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Estatus { get; set; }
        public string RutaImagen { get; set; }
        public string Linea { get; set; }
        public Nullable<int> Orden { get; set; }
        public string SubLinea { get; set; }
        public Nullable<long> Exclusividad { get; set; }
        public bool Intercambiable { get; set; }
        public bool tieneVeta { get; set; }
    
        public virtual ArtSubLinea ArtSubLinea { get; set; }
        public virtual EstatusCatalogo EstatusCatalogo { get; set; }
        public virtual Exclusividade Exclusividade { get; set; }
    }
}
