//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticulosAdjunto
    {
        public int IdArticuloAdjunto { get; set; }
        public string CodigoADN { get; set; }
        public string CodigoADNAdjunto { get; set; }
        public int Cantidad { get; set; }
    }
}
