//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticulosFav
    {
        public long IdArtFavorito { get; set; }
        public int Usuario { get; set; }
        public long Articulo { get; set; }
        public Nullable<System.DateTime> FechaFavorito { get; set; }
    
        public virtual ProyArticulo ProyArticulo { get; set; }
        public virtual User User { get; set; }
    }
}
