//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticulosFav
    {
        public long IdArtFavorito { get; set; }
        public int Usuario { get; set; }
        public long Articulo { get; set; }
        public Nullable<System.DateTime> FechaFavorito { get; set; }
    
        public virtual ProyArticulo ProyArticulo { get; set; }
        public virtual User User { get; set; }
    }
}
