//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtJaladera
    {
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Estatus { get; set; }
        public string Linea { get; set; }
        public string RutaImagen { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> PuertaAnchoMin { get; set; }
        public Nullable<int> PuertaAltoMin { get; set; }
        public Nullable<int> FrenteAnchoMin { get; set; }
        public Nullable<int> FrenteAltoMin { get; set; }
    
        public virtual EstatusCatalogo EstatusCatalogo { get; set; }
    }
}
