//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtTipos
    {
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Estatus { get; set; }
        public Nullable<int> Orden { get; set; }
        public string RutaImagen { get; set; }
        public bool tieneVidrio { get; set; }
        public bool EquivalenteM2 { get; set; }
        public int MinimoCompra { get; set; }
        public Nullable<decimal> EquivalenciaM2 { get; set; }
    
        public virtual EstatusCatalogo EstatusCatalogo { get; set; }
    }
}
