//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapturasPago
    {
        public System.Guid idCapturaPago { get; set; }
        public int Proyecto { get; set; }
        public System.DateTime TmCaptura { get; set; }
        public System.DateTime TmPago { get; set; }
        public string Folio { get; set; }
        public decimal Monto { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Proyecto Proyecto1 { get; set; }
    }
}
