//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapturasPago
    {
        public System.Guid idCapturaPago { get; set; }
        public int Proyecto { get; set; }
        public System.DateTime TmCaptura { get; set; }
        public System.DateTime TmPago { get; set; }
        public string Folio { get; set; }
        public decimal Monto { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Proyecto Proyecto1 { get; set; }
    }
}
