//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoEstado
    {
        public CatalogoEstado()
        {
            this.CatalogoCiudades = new HashSet<CatalogoCiudade>();
        }
    
        public string Estado { get; set; }
        public string Descripcion { get; set; }
        public string Abreviacion { get; set; }
        public string Especial { get; set; }
        public bool Marcado { get; set; }
    
        public virtual ICollection<CatalogoCiudade> CatalogoCiudades { get; set; }
    }
}
