//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoEstado
    {
        public CatalogoEstado()
        {
            this.CatalogoCiudades = new HashSet<CatalogoCiudade>();
        }
    
        public string Estado { get; set; }
        public string Descripcion { get; set; }
        public string Abreviacion { get; set; }
        public string Especial { get; set; }
        public bool Marcado { get; set; }
    
        public virtual ICollection<CatalogoCiudade> CatalogoCiudades { get; set; }
    }
}
