//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoCiudade
    {
        public CatalogoCiudade()
        {
            this.MatrizFletes = new HashSet<MatrizFlete>();
            this.MatrizFletes2 = new HashSet<MatrizFletes2>();
        }
    
        public int CatalogoCiudadId { get; set; }
        public string Estado { get; set; }
        public string Ciudad { get; set; }
        public string Descripcion { get; set; }
        public string Rango1 { get; set; }
        public string Rango2 { get; set; }
        public string Rango3 { get; set; }
        public string Rango4 { get; set; }
        public string Especial { get; set; }
        public bool Marcado { get; set; }
    
        public virtual CatalogoEstado CatalogoEstado { get; set; }
        public virtual ICollection<MatrizFlete> MatrizFletes { get; set; }
        public virtual ICollection<MatrizFletes2> MatrizFletes2 { get; set; }
    }
}
