//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exclusividade
    {
        public Exclusividade()
        {
            this.ArtColores = new HashSet<ArtColore>();
        }
    
        public long IdExclusividad { get; set; }
        public int Usuario { get; set; }
        public System.DateTime Caducidad { get; set; }
        public string LineaExclusiva { get; set; }
        public string BaseExclusiva { get; set; }
        public string ColorExclusivo { get; set; }
        public string CubrecantoExclusivo { get; set; }
        public string JaladeraExclusiva { get; set; }
    
        public virtual ICollection<ArtColore> ArtColores { get; set; }
        public virtual User User { get; set; }
    }
}
