//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavArticulo
    {
        public long IdArticulo { get; set; }
        public int Favorito { get; set; }
        public int Cantidad { get; set; }
        public string Unidad { get; set; }
        public string ADNTipo { get; set; }
        public string ADNBase { get; set; }
        public string ADNColor { get; set; }
        public string ADNCubrecanto { get; set; }
        public string ADNVeta { get; set; }
        public string ADNVariante { get; set; }
        public string CodigoADNBase { get; set; }
        public string CodigoADNInterno { get; set; }
        public bool tieneJaladera { get; set; }
        public bool tieneVidrio { get; set; }
        public bool tieneProtecta { get; set; }
        public bool tieneOrificios { get; set; }
        public string UnidadJaladera { get; set; }
        public string ADNJaladeraBase { get; set; }
        public string ADNJaladera { get; set; }
        public string ADNJaladeraOpcion { get; set; }
        public string CodigoADNJaladera { get; set; }
        public string ADNPosicionJaladera { get; set; }
        public string ADNVidrioBase { get; set; }
        public string ADNVidrioColor { get; set; }
        public string CodigoADNVidrio { get; set; }
        public string ADNProtectaBase { get; set; }
        public string ADNProtectaColor { get; set; }
        public string CodigoADNProtecta { get; set; }
        public string ADNOrificios { get; set; }
        public Nullable<short> OrificiosDistCanto { get; set; }
        public Nullable<byte> OrificiosCuantos { get; set; }
        public string CodigoADNOrificios { get; set; }
        public Nullable<int> Alto { get; set; }
        public Nullable<int> Ancho { get; set; }
    
        public virtual Favorito Favorito1 { get; set; }
    }
}
