//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorito
    {
        public Favorito()
        {
            this.FavArticulos = new HashSet<FavArticulo>();
        }
    
        public int IdFavorito { get; set; }
        public int Usuario { get; set; }
        public string ClienteERP { get; set; }
        public Nullable<System.DateTime> FechaFavorito { get; set; }
        public Nullable<bool> Exhibicion { get; set; }
        public string Observaciones { get; set; }
        public int Proyecto { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<FavArticulo> FavArticulos { get; set; }
        public virtual User User { get; set; }
    }
}
