//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fletera
    {
        public Fletera()
        {
            this.MatrizFletes = new HashSet<MatrizFlete>();
            this.MatrizFletes2 = new HashSet<MatrizFletes2>();
            this.Users = new HashSet<User>();
        }
    
        public int FleteraId { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<MatrizFlete> MatrizFletes { get; set; }
        public virtual ICollection<MatrizFletes2> MatrizFletes2 { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
