//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fletera
    {
        public Fletera()
        {
            this.MatrizFletes = new HashSet<MatrizFlete>();
            this.MatrizFletes2 = new HashSet<MatrizFletes2>();
            this.Users = new HashSet<User>();
        }
    
        public int FleteraId { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<MatrizFlete> MatrizFletes { get; set; }
        public virtual ICollection<MatrizFletes2> MatrizFletes2 { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
