//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrizFlete
    {
        public int ElementoMatrizId { get; set; }
        public int FleteraId { get; set; }
        public int CatalogoCiudadId { get; set; }
        public decimal PaqChicoM2 { get; set; }
        public decimal PaqMedioM2 { get; set; }
        public decimal PaqGrandeM2 { get; set; }
    
        public virtual CatalogoCiudade CatalogoCiudade { get; set; }
        public virtual Fletera Fletera { get; set; }
    }
}
