//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrizFlete
    {
        public int ElementoMatrizId { get; set; }
        public int FleteraId { get; set; }
        public int CatalogoCiudadId { get; set; }
        public decimal PaqChicoM2 { get; set; }
        public decimal PaqMedioM2 { get; set; }
        public decimal PaqGrandeM2 { get; set; }
    
        public virtual CatalogoCiudade CatalogoCiudade { get; set; }
        public virtual Fletera Fletera { get; set; }
    }
}
