//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaxMinBaseColor
    {
        public int IdMaxMin { get; set; }
        public string Base { get; set; }
        public string Color { get; set; }
        public int AnchoMax { get; set; }
        public int AnchoMin { get; set; }
        public int AltoMax { get; set; }
        public int AltoMin { get; set; }
    }
}
