//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaxMinAcabado
    {
        public int IdMaxMin { get; set; }
        public string Color { get; set; }
        public int AnchoMax { get; set; }
        public int AnchoMin { get; set; }
        public int AltoMax { get; set; }
        public int AltoMin { get; set; }
    }
}
