//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaxMinColor
    {
        public int idRestriccionColor { get; set; }
        public string Color { get; set; }
        public Nullable<int> AnchoMax { get; set; }
        public Nullable<int> AnchoMin { get; set; }
        public Nullable<int> AltoMax { get; set; }
        public Nullable<int> AltoMin { get; set; }
    }
}
