//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedidasFija
    {
        public int IdMedidaFija { get; set; }
        public string Tipo { get; set; }
        public string Base { get; set; }
        public string Color { get; set; }
        public string Veta { get; set; }
        public string Cubrecanto { get; set; }
        public string Variante { get; set; }
        public int Ancho { get; set; }
        public int Alto { get; set; }
        public string Estatus { get; set; }
        public string Medida { get; set; }
    }
}
