//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedidasFija
    {
        public int IdMedidaFija { get; set; }
        public string Tipo { get; set; }
        public string Base { get; set; }
        public string Color { get; set; }
        public string Veta { get; set; }
        public string Cubrecanto { get; set; }
        public string Variante { get; set; }
        public int Ancho { get; set; }
        public int Alto { get; set; }
        public string Estatus { get; set; }
        public string Medida { get; set; }
    }
}
