//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedidaRegla
    {
        public int idReglaMedida { get; set; }
        public string Tipo { get; set; }
        public string Base { get; set; }
        public Nullable<int> AnchoMax { get; set; }
        public Nullable<int> AnchoMin { get; set; }
        public Nullable<int> AltoMax { get; set; }
        public Nullable<int> AltoMin { get; set; }
        public Nullable<decimal> Multiplo70 { get; set; }
        public Nullable<decimal> Multiplo72 { get; set; }
        public Nullable<decimal> Multiplo76 { get; set; }
        public Nullable<decimal> Multiplo80 { get; set; }
        public string PosicionJaladeras { get; set; }
        public Nullable<decimal> EquivalenciaM2 { get; set; }
        public string SubLinea { get; set; }
    }
}
