//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multiplos
    {
        public int IdMultiplo { get; set; }
        public string Tipo { get; set; }
        public string Base { get; set; }
        public string Estandar { get; set; }
        public int Medida { get; set; }
        public string Linea { get; set; }
        public string Sublinea { get; set; }
    }
}
