//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multiplos
    {
        public int IdMultiplo { get; set; }
        public string Tipo { get; set; }
        public string Base { get; set; }
        public string Estandar { get; set; }
        public int Medida { get; set; }
        public string Linea { get; set; }
        public string Sublinea { get; set; }
    }
}
