//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Mensaje { get; set; }
        public string Referencias { get; set; }
        public string URL { get; set; }
        public System.DateTime Alta { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public string Tipo { get; set; }
        public string ClienteERP { get; set; }
        public bool Leida { get; set; }
        public string Estatus { get; set; }
    }
}
