//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Mensaje { get; set; }
        public string Referencias { get; set; }
        public string URL { get; set; }
        public System.DateTime Alta { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public string Tipo { get; set; }
        public string ClienteERP { get; set; }
        public bool Leida { get; set; }
        public string Estatus { get; set; }
    }
}
