//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oportunidade
    {
        public long IdOportunidad { get; set; }
        public int Usuario { get; set; }
        public System.DateTime Caducidad { get; set; }
        public string LineaAbierta { get; set; }
        public string BaseAbierta { get; set; }
        public string ColorAbierto { get; set; }
        public string CubrecantoAbierto { get; set; }
        public string JaladeraAbierta { get; set; }
    
        public virtual User User { get; set; }
    }
}
