//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oportunidade
    {
        public long IdOportunidad { get; set; }
        public int Usuario { get; set; }
        public System.DateTime Caducidad { get; set; }
        public string LineaAbierta { get; set; }
        public string BaseAbierta { get; set; }
        public string ColorAbierto { get; set; }
        public string CubrecantoAbierto { get; set; }
        public string JaladeraAbierta { get; set; }
    
        public virtual User User { get; set; }
    }
}
