//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public string NombreParametro { get; set; }
        public string ValorCadena { get; set; }
        public Nullable<int> ValorEntero { get; set; }
        public Nullable<decimal> ValorDecimal { get; set; }
        public Nullable<double> ValorDoble { get; set; }
        public Nullable<System.DateTime> ValorTiempo { get; set; }
        public Nullable<bool> ValorBooleano { get; set; }
    }
}
