//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public string NombreParametro { get; set; }
        public string ValorCadena { get; set; }
        public Nullable<int> ValorEntero { get; set; }
        public Nullable<decimal> ValorDecimal { get; set; }
        public Nullable<double> ValorDoble { get; set; }
        public Nullable<System.DateTime> ValorTiempo { get; set; }
        public Nullable<bool> ValorBooleano { get; set; }
    }
}
