//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyNota
    {
        public long IdNotaProyecto { get; set; }
        public int Proyecto { get; set; }
        public int Usuario { get; set; }
        public System.DateTime TmNota { get; set; }
        public string Texto { get; set; }
    
        public virtual User User { get; set; }
        public virtual Proyecto Proyecto1 { get; set; }
    }
}
