//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        public Proyecto()
        {
            this.CapturasPagos = new HashSet<CapturasPago>();
            this.ProyArticulos = new HashSet<ProyArticulo>();
            this.ProyNotas = new HashSet<ProyNota>();
        }
    
        public int IdProyecto { get; set; }
        public int Usuario { get; set; }
        public string ClienteERP { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> TmRegistrado { get; set; }
        public Nullable<System.DateTime> TmSolicitado { get; set; }
        public Nullable<System.DateTime> TmAprobado { get; set; }
        public Nullable<System.DateTime> TmCerrado { get; set; }
        public Nullable<System.DateTime> TmEntregaTentativa { get; set; }
        public Nullable<System.DateTime> FechaRequerida { get; set; }
        public Nullable<int> CodigoInterno { get; set; }
        public Nullable<int> PedidoInterno { get; set; }
        public Nullable<int> OrdenProdInterna { get; set; }
        public Nullable<int> FacturaInterna { get; set; }
        public string ReferenciaCliente { get; set; }
        public bool Exhibicion { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> UserRevisado { get; set; }
        public Nullable<int> UserAprobado { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<System.DateTime> UltimoSeguimiento { get; set; }
        public Nullable<decimal> PctDescuento { get; set; }
        public string Direccion { get; set; }
        public string Poblacion { get; set; }
        public string Colonia { get; set; }
        public string CodigoPostal { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string Telefono { get; set; }
        public Nullable<bool> EnvioOcurre { get; set; }
        public Nullable<bool> EnvioAsegurado { get; set; }
        public Nullable<bool> EntregaEnPlanta { get; set; }
        public Nullable<bool> EnvioCobrado { get; set; }
        public string FormaDeEnvio { get; set; }
        public string GuiaEmbarque { get; set; }
        public Nullable<bool> ExhibicionAprobado { get; set; }
        public string LoteProdInterno { get; set; }
        public string SubLinea { get; set; }
        public bool EsExpress { get; set; }
        public Nullable<long> ArticuloFlete { get; set; }
        public Nullable<long> ArticuloSeguro { get; set; }
        public Nullable<decimal> CostoPaqueteChico { get; set; }
        public Nullable<decimal> CostoPaqueteMediano { get; set; }
        public Nullable<decimal> CostoPaqueteGrande { get; set; }
        public Nullable<int> FleteraId { get; set; }
        public Nullable<decimal> Costo_1_3_c { get; set; }
        public Nullable<decimal> Costo_4_10_c { get; set; }
        public Nullable<decimal> Costo_11_20_c { get; set; }
        public Nullable<decimal> Costo_21up_c { get; set; }
        public Nullable<decimal> Costo_1_3_p { get; set; }
        public Nullable<decimal> Costo_4_10_p { get; set; }
        public Nullable<decimal> Costo_11_20_p { get; set; }
        public Nullable<decimal> Costo_21up_p { get; set; }
        public Nullable<int> CajasChicas { get; set; }
        public Nullable<int> CajasMedianas { get; set; }
        public Nullable<int> Paquetes { get; set; }
        public Nullable<int> Cilindros { get; set; }
        public bool TieneMuebles { get; set; }
        public Nullable<int> Vendedor { get; set; }
        public Nullable<System.DateTime> TmValidado { get; set; }
        public bool ValidaTiempsEntrega { get; set; }
    
        public virtual ICollection<CapturasPago> CapturasPagos { get; set; }
        public virtual ICollection<ProyArticulo> ProyArticulos { get; set; }
        public virtual ICollection<ProyNota> ProyNotas { get; set; }
    }
}
