//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ArtColoresExclusivos = new HashSet<ArtColoresExclusivo>();
            this.ArticulosFavs = new HashSet<ArticulosFav>();
            this.Exclusividades = new HashSet<Exclusividade>();
            this.Favoritos = new HashSet<Favorito>();
            this.LineasUsuarios = new HashSet<LineasUsuario>();
            this.Oportunidades = new HashSet<Oportunidade>();
            this.PaseHists = new HashSet<PaseHist>();
            this.ProyNotas = new HashSet<ProyNota>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string NombreCompleto { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public string Email { get; set; }
        public string Comment { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public Nullable<System.DateTime> DateLastActivity { get; set; }
        public System.DateTime DateLastPasswordChange { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string ClienteERP { get; set; }
        public string AgenteServicio { get; set; }
        public Nullable<bool> PuedeExpress { get; set; }
        public Nullable<int> FleteraId { get; set; }
        public Nullable<bool> FleteAutomatico { get; set; }
        public Nullable<System.DateTime> UltimaVisitaDocumentos { get; set; }
        public Nullable<bool> ClienteMuebles { get; set; }
        public string ZonaImpuesto { get; set; }
        public string ListaPreciosEsp { get; set; }
    
        public virtual ICollection<ArtColoresExclusivo> ArtColoresExclusivos { get; set; }
        public virtual ICollection<ArticulosFav> ArticulosFavs { get; set; }
        public virtual ICollection<Exclusividade> Exclusividades { get; set; }
        public virtual ICollection<Favorito> Favoritos { get; set; }
        public virtual Fletera Fletera { get; set; }
        public virtual ICollection<LineasUsuario> LineasUsuarios { get; set; }
        public virtual ICollection<Oportunidade> Oportunidades { get; set; }
        public virtual ICollection<PaseHist> PaseHists { get; set; }
        public virtual ICollection<ProyNota> ProyNotas { get; set; }
    }
}
