//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;

    [Table("UserProfile")]
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }

        [Key]
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string ClienteERP { get; set; }
        public string NombreCompleto { get; set; }
        public string Email { get; set; }
        public string AgenteServicio { get; set; }
        public Nullable<bool> PuedeExpress { get; set; }
        public Nullable<int> FleteraId { get; set; }
        public Nullable<bool> FleteAutomatico { get; set; }
        public Nullable<System.DateTime> UltimaVistaDocumentos { get; set; }
        public Nullable<bool> ClienteMuebles { get; set; }
        public string ZonaImpuesto { get; set; }
        public string ListaPreciosEsp { get; set; }
        public Nullable<int> UserOld { get; set; }
        public bool Estatus { get; set; }
    
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
