//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAcumuladosColor
    {
        public string Nombre { get; set; }
        public Nullable<int> Piezas { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Metraje { get; set; }
        public int Proyecto { get; set; }
    }
}
