//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vArticulosFavorito
    {
        public long IdArticulo { get; set; }
        public int Favorito { get; set; }
        public int Cantidad { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Ancho { get; set; }
        public Nullable<int> Alto { get; set; }
    }
}
