//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vNotasProyecto
    {
        public long IdNotaProyecto { get; set; }
        public int Proyecto { get; set; }
        public int Usuario { get; set; }
        public string NombreCompleto { get; set; }
        public string UserName { get; set; }
        public System.DateTime TmNota { get; set; }
        public int esNueva { get; set; }
        public string Texto { get; set; }
    }
}
