//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOportunidade
    {
        public long IdOportunidad { get; set; }
        public int Usuario { get; set; }
        public System.DateTime Caducidad { get; set; }
        public string TipoComponente { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string RutaImagen { get; set; }
    }
}
