//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProyectosPorRevisar
    {
        public string NomEstatus { get; set; }
        public string Estatus { get; set; }
        public int IdProyecto { get; set; }
        public Nullable<System.DateTime> TmSolicitado { get; set; }
        public string NombreCliente { get; set; }
        public Nullable<decimal> PrecioTotal { get; set; }
        public Nullable<int> NumArticulos { get; set; }
        public string ReferenciaCliente { get; set; }
        public string Revisado { get; set; }
        public Nullable<int> UserAprobado { get; set; }
        public Nullable<int> UserRevisado { get; set; }
        public int Usuario { get; set; }
        public Nullable<System.DateTime> TmRegistrado { get; set; }
        public Nullable<System.DateTime> TmEntregaTentativa { get; set; }
        public Nullable<int> CodigoInterno { get; set; }
        public Nullable<int> PedidoInterno { get; set; }
        public Nullable<int> OrdenProdInterna { get; set; }
        public Nullable<int> FacturaInterna { get; set; }
        public string LoteProdInterno { get; set; }
        public string GuiaEmbarque { get; set; }
        public Nullable<bool> EsExpress { get; set; }
        public Nullable<bool> FleteAutomatico { get; set; }
    }
}
