//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProyectosPorRevisar
    {
        public string NomEstatus { get; set; }
        public string Estatus { get; set; }
        public int IdProyecto { get; set; }
        public Nullable<System.DateTime> TmSolicitado { get; set; }
        public string NombreCliente { get; set; }
        public Nullable<decimal> PrecioTotal { get; set; }
        public Nullable<int> NumArticulos { get; set; }
        public string ReferenciaCliente { get; set; }
        public string Revisado { get; set; }
        public Nullable<int> UserAprobado { get; set; }
        public Nullable<int> UserRevisado { get; set; }
        public int Usuario { get; set; }
        public Nullable<System.DateTime> TmRegistrado { get; set; }
        public Nullable<System.DateTime> TmEntregaTentativa { get; set; }
        public Nullable<int> CodigoInterno { get; set; }
        public Nullable<int> PedidoInterno { get; set; }
        public Nullable<int> OrdenProdInterna { get; set; }
        public Nullable<int> FacturaInterna { get; set; }
        public string LoteProdInterno { get; set; }
        public string GuiaEmbarque { get; set; }
        public Nullable<bool> EsExpress { get; set; }
        public Nullable<bool> FleteAutomatico { get; set; }
    }
}
