//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProyectosAprobado
    {
        public int IdProyecto { get; set; }
        public int Usuario { get; set; }
        public Nullable<System.DateTime> TmRegistrado { get; set; }
        public Nullable<System.DateTime> TmSolicitado { get; set; }
        public string ReferenciaCliente { get; set; }
        public Nullable<int> NumArticulos { get; set; }
    }
}
