//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProyectosSolicitado
    {
        public int IdProyecto { get; set; }
        public int Usuario { get; set; }
        public Nullable<System.DateTime> TmRegistrado { get; set; }
        public Nullable<System.DateTime> TmSolicitado { get; set; }
        public string ReferenciaCliente { get; set; }
        public string Estatus { get; set; }
        public Nullable<int> NumArticulos { get; set; }
        public Nullable<bool> EsExpress { get; set; }
    }
}
