//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalInnovika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUsuario
    {
        public string RoleName { get; set; }
        public string UserName { get; set; }
        public int UserId { get; set; }
        public string NombreCompleto { get; set; }
        public string Email { get; set; }
        public string Comment { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public Nullable<System.DateTime> DateLastActivity { get; set; }
        public System.DateTime DateLastPasswordChange { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string ClienteERP { get; set; }
        public string PasswordHash { get; set; }
        public string PerfilCompra { get; set; }
        public Nullable<bool> CambiarPase { get; set; }
        public Nullable<bool> PuedeExpress { get; set; }
        public Nullable<bool> FleteAutomatico { get; set; }
        public Nullable<int> FleteraId { get; set; }
        public Nullable<bool> ClienteMuebles { get; set; }
    }
}
